#spring:
#  h2:
#    console:
#      enable: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:tcp:project
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#jpa:
#  hibernate:
#    ddl-auto: create
#  show-sql: true
#  generate-ddl: true
#  properties:
#    hibernate:
#      format_sql: true
#
#logging.level:
#  org.hibernate.SQL: error
